version: '3.8'

services:
  prtg-monitor:
    image: tommmy-ctrl/prtg-monitor:latest

    environment:
      - PYTHONUNBUFFERED=1

    container_name: prtg-service-linux
    restart: unless-stopped
    volumes:
      - ./config/config.ini:/app/config/config.ini:ro
      - ./data:/app/data