version: '3.8'

services:
  prtg-monitor:
    image: dein-dockerhub-name/prtg-monitor:latest  # <--- HIER ÄNDERN
    container_name: prtg-monitor-py
    restart: unless-stopped
    volumes:
      - /pfad/auf/deinem/docker/host/config:/app/config/config.ini:ro
      - /pfad/auf/deinem/docker/host/data:/app/data