services:
  prtg-monitor:
    build: .
    container_name: prtg-monitor-py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/app/config
    networks:
      - db_network_external

networks:
  db_network_external:
    name: database-stack_db_network
    external: true