services:
  prtg-monitor:
    build: .
    container_name: prtg-monitor-py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mounts the local 'config' folder as read-only into the container.
      # This folder is ignored by Git.
      - ./config:/app/config:ro
      # Mounts the local 'data' folder, in case the script writes files.
      - ./data:/app/data
    networks:
      - db_network_external

networks:
  db_network_external:
    # Connects to the database stack's network.
    name: database-stack_db_network
    external: true